[build]
  base = "VoucherApp"  # Base directory
  command = "npm run build"  # Build command
  publish = "VoucherApp/build"  # Publish directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
